type = "about"
title = "About"

[profile]
research_interests = [
  "Generative AI",
  "World Models",
  "Agentic RL"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"


[[sections]]
id = "news"
type = "list"
title = "News"
source = "news.toml"


[[sections]]
id = "publications"
type = "publications"
title = "Publications"
