[[news]]
date = "2026-09"
content = "Three papers were accepted to NeurIPS2026 🎉"

[[news]]
date = "2026-05"
content = "One paper was accepted to KDD2026, Main Track (Research) (Co-First Author) 🎉"

[[news]]
date = "2026-05"
content = "One paper was accepted to ICML2026, (Co-First Author) 🎉"

[[news]]
date = "2025-11"
content = "One paper was accepted to KDD2026, Main Track (Research) (First Author) 🎉"

[[news]]
date = "2025-11"
content = "Two papers were accepted to AAAI2026, Congrats to All 🎉"

[[news]]
date = "2025-09"
content = "One paper was accepted to NeurIPS2025 (First Author) 🎉"
