[[news]]
date = "2026-09"
content = "三篇论文被NeurIPS2026录用（第一作者一篇，通讯作者两篇）🎉"

[[news]]
date = "2026-05"
content = "一篇论文被KDD2026 Main Track（研究）接收（共同第一作者）🎉"

[[news]]
date = "2026-05"
content = "一篇论文被ICML2026录用，（共同第一作者）🎉"

[[news]]
date = "2025-11"
content = "一篇论文被KDD2026 Main Track（研究）接收（第一作者）🎉"

[[news]]
date = "2025-11"
content = "两篇论文被AAAI2026接收，恭喜大家🎉"

[[news]]
date = "2025-09"
content = "一篇论文被NeurIPS2025录用（第一作者）🎉"


